name: Deploy to Firebase Hosting Preview
on:
  pull_request:
    branches:
      - live

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: GCP authentication
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Fetch resume
        run: gsutil cp gs://${{ secrets.GCP_BUCKET }}/resume.ts src/resume.ts

      - name: Fetch environment variables
        run: gsutil cp gs://${{ secrets.GCP_BUCKET }}/.env .

      - name: Build
        run: npm ci && npm run build

      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          expires: 1h
          projectId: aliarsen-portfolio